##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: _view
publish_to: none

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.3.1 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  _data:
    path: ../_data
  _service_interfaces:
    path: ../_service_interfaces

  xyz_gen_annotations: ^0.49.0
  xyz_pod: ^0.43.1
  xyz_utils: ^0.62.0
  xyz_flutter_plus: ^0.54.0

  cupertino_icons: any
  equatable: any
  fluentui_system_icons: any # see: https://github.com/microsoft/fluentui-system-icons/
  go_router: any
  google_fonts: any
  meta: any
  flutter_svg: any

## -----------------------------------------------------------------------------

dependency_overrides:
  # TODO: Comment out these lines if you don't have these packages at their
  # respective paths. They are included for development purposes to allow
  # simultaneous work on this package and its dependencies.
  xyz_config:
    path: ../../xyz_config
  xyz_gen_annotations:
    path: ../../xyz_gen/xyz_gen_annotations
  xyz_pod:
    path: ../../xyz_pod
  xyz_utils:
    path: ../../xyz_utils
  xyz_flutter_plus:
    path: ../../xyz_flutter_plus

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

## -----------------------------------------------------------------------------

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/app_icon_background_maskable/
    - assets/icons/app_icon_background/
    - assets/icons/app_icon_foreground/
    - assets/icons/app_icon_maskable/
    - assets/icons/app_icon/
    - assets/svg_icons/
