##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## X|Y|Z & Dev
##
## Copyright Ⓒ Robert Mollentze, xyzand.dev
## 
## Licensing details can be found in the LICENSE file in the root directory.
## 
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: _view
publish_to: none

## -----------------------------------------------------------------------------

environment:

  sdk: '>=3.0.0 <4.0.0'

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter

  _data:
    path: ../_data
  _service_interfaces:
    path: ../_service_interfaces

  xyz_flutter_plus: ^0.38.0
  xyz_gen_annotations: ^0.15.0
  xyz_pod: ^0.23.0
  xyz_utils: ^0.51.0

  cupertino_icons: any
  equatable: any
  fluentui_system_icons: any # see: https://github.com/microsoft/fluentui-system-icons/
  go_router: any
  google_fonts: any
  meta: any
  flutter_svg: any

## -----------------------------------------------------------------------------

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: any  

## -----------------------------------------------------------------------------

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/app_icon/