//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'app_scale_type.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

extension AppScaleTypeUtils on AppScaleType {
  AppScaleType get next {
    final index = (this.index + 1) % AppScaleType.values.length;
    return AppScaleType.values[index];
  }

  AppScaleType get previous {
    final index = (this.index - 1 + AppScaleType.values.length) %
        AppScaleType.values.length;
    return AppScaleType.values[index];
  }

  String trFromSection(String section) {
    return '${this.friendlyName}||$section.${this.name}'.tr();
  }

  String get friendlyName {
    return this
        .name
        .toSnakeCase()
        .split('_')
        .map((e) => e.capitalize())
        .join(' ');
  }
}
