//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

part of 'app_locale_type.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

extension AppLocaleTypeUtils on AppLocaleType {
  AppLocaleType get next {
    final index = (this.index + 1) % AppLocaleType.values.length;
    return AppLocaleType.values[index];
  }

  AppLocaleType get previous {
    final index = (this.index - 1 + AppLocaleType.values.length) %
        AppLocaleType.values.length;
    return AppLocaleType.values[index];
  }

  String trFromSection(String section, [Map args = const {}]) {
    return '${this.friendlyName}||$section.${this.name}'.tr(args: args);
  }

  String get friendlyName {
    return this
        .name
        .toSnakeCase()
        .split('_')
        .map((e) => e.capitalize())
        .join(' ');
  }
}
